let DATA;const $=s=>document.querySelector(s),fmt=n=>n.toLocaleString(),pct=(a,b)=>b?100*a/b:0,month=d=>d.slice(0,7),dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),monthLabel=m=>new Date(m+'-02T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'});let charts=new Map();
fetch('data.json').then(r=>r.json()).then(d=>{d.records=d.records.map(r=>({firstServiceDate:r[0],active:r[1],count:r[2]}));DATA=d;$('#asof').textContent='Report snapshot: Sep 21, 2026 at 1:11 PM MDT';$('#report-total').textContent=fmt(d.validation.reportUniqueCustomers);$('#report-active').textContent=fmt(d.validation.activeCustomers);$('#report-frozen').textContent=fmt(d.validation.frozenCustomers);const min=d.records[0].firstServiceDate,max=d.records[d.records.length-1].firstServiceDate;for(const s of ['#start','#end','#cutoff']){$(s).min=min;$(s).max=max}$('#start').value=max.slice(0,8)+'01';$('#end').value=max;$('#cutoff').value=max;$('#trend-subtitle').textContent='Each point is one monthly first-service cohort. Every customer shown has been in the report cohort for at least 12 months as of Sep 21, 2026. Filters above do not change this line.';render()});
const mode=()=>document.querySelector('input[name="mode"]:checked').value;for(const s of ['#start','#end','#cutoff'])$(s).addEventListener('change',render);document.querySelectorAll('input[name="mode"]').forEach(x=>x.addEventListener('change',()=>{syncMode();render()}));$('#reset').onclick=()=>{document.querySelector('input[name="mode"][value="range"]').checked=true;$('#start').value=$('#end').max.slice(0,8)+'01';$('#end').value=$('#end').max;$('#cutoff').value=$('#cutoff').max;syncMode();render()};
function syncMode(){let range=mode()==='range';document.querySelectorAll('.range-control').forEach(x=>x.hidden=!range);document.querySelector('.cutoff-control').hidden=range}
function selected(){if(!DATA)return[];if(mode()==='cumulative'){let c=$('#cutoff').value;return DATA.records.filter(r=>r.firstServiceDate<=c)}let a=$('#start').value,b=$('#end').value;if(a>b)return[];return DATA.records.filter(r=>r.firstServiceDate>=a&&r.firstServiceDate<=b)}
function render(){if(!DATA)return;let isRange=mode()==='range',invalid=isRange&&$('#start').value>$('#end').value,rs=selected(),base=rs.reduce((a,r)=>a+r.count,0),active=rs.reduce((a,r)=>a+r.active*r.count,0),rate=pct(active,base),label=isRange?`${dateLabel($('#start').value)} - ${dateLabel($('#end').value)}`:`On or before ${dateLabel($('#cutoff').value)}`;$('#selection').classList.toggle('error',invalid);$('#selection').textContent=invalid?'Start date must be on or before end date.':`${isRange?'DATE RANGE':'CUMULATIVE'} · Earliest report Initial Service ${isRange?'from '+label.toLowerCase():'on or before '+dateLabel($('#cutoff').value)}`;$('#metric-title').textContent=isRange?'Selected first-service date range':'Cumulative through selected cutoff';$('#metric-subtitle').textContent=invalid?'Invalid date range':label;$('#rate').textContent=base?rate.toFixed(1)+'%':'-';$('#attr').textContent=base?(100-rate).toFixed(1)+'% frozen':'No customers match';$('#base').textContent=fmt(base);$('#active').textContent=fmt(active);$('#frozen').textContent=fmt(base-active);detail(rs);trend()}
function detail(rs){let m={};for(const r of rs){let k=month(r.firstServiceDate),x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}let a=Object.entries(m).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,36);$('#detail').innerHTML=a.length?a.map(([k,[b,ac]])=>`<tr><td>${monthLabel(k)}</td><td>${fmt(b)}</td><td>${fmt(ac)}</td><td>${fmt(b-ac)}</td><td>${pct(ac,b).toFixed(1)}%</td><td>${(100-pct(ac,b)).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No customers match</td></tr>'}
function trend(){let cutoff=new Date('2026-09-21T12:00:00');cutoff.setFullYear(cutoff.getFullYear()-1);let m={};for(const r of DATA.records){let k=month(r.firstServiceDate),x=m[k]||(m[k]=[0,0]);x[0]+=r.count;x[1]+=r.active*r.count}let keys=Object.keys(m).sort().filter(k=>{let e=new Date(k+'-01T12:00:00');e.setMonth(e.getMonth()+1);e.setDate(0);return e<=cutoff});let vals=keys.map(k=>{let[b,a]=m[k];return{value:pct(a,b),base:b,active:a}});line($('#trend'),keys,vals)}
function setup(c){let w=c.clientWidth||800,h=Math.max(230,Math.min(320,w*.34)),dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;c.style.height=h+'px';let x=c.getContext('2d');x.scale(dpr,dpr);return[x,w,h]}
function axes(x,w,h){x.strokeStyle='#dfe7f0';x.fillStyle='#6b7a90';x.font='11px system-ui';for(let i=0;i<=4;i++){let y=15+(h-50)*i/4;x.beginPath();x.moveTo(45,y);x.lineTo(w-10,y);x.stroke();x.fillText((100*(1-i/4)).toFixed(0)+'%',2,y+4)}}
function bind(c,points){charts.set(c,points);if(c.dataset.tip)return;c.dataset.tip=1;for(const ev of ['mousemove','click','touchstart'])c.addEventListener(ev,e=>{let r=c.getBoundingClientRect(),q=e.touches?e.touches[0]:e,x=q.clientX-r.left,y=q.clientY-r.top,ps=charts.get(c);if(!ps.length){hideTip();return}let p=ps.reduce((a,b)=>Math.hypot(b.x-x,b.y-y)<Math.hypot(a.x-x,a.y-y)?b:a,ps[0]);if(Math.abs(p.x-x)>35){hideTip();return}showTip(c,p.x,p.y,`First-service cohort: ${monthLabel(p.label)}<b>${p.value.toFixed(1)}% active</b>${fmt(p.active)} of ${fmt(p.base)} report customers active`)}) ;c.addEventListener('mouseleave',hideTip)}
function showTip(c,x,y,html){let t=$('#tooltip'),r=c.getBoundingClientRect();t.innerHTML=html;t.style.display='block';t.style.left=Math.min(innerWidth-t.offsetWidth-8,r.left+x+12)+'px';t.style.top=Math.max(8,r.top+y-t.offsetHeight-10)+'px'}function hideTip(){$('#tooltip').style.display='none'}
function line(c,labels,vals){let[x,w,h]=setup(c);axes(x,w,h);let ps=vals.map((v,i)=>({x:45+(w-65)*i/(vals.length-1||1),y:15+(h-50)*(1-v.value/100),value:v.value,base:v.base,active:v.active,label:labels[i]}));x.strokeStyle='#1478f2';x.lineWidth=2;x.beginPath();ps.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.stroke();x.fillStyle='#1478f2';let stride=w<500?6:3;ps.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,3,0,7);x.fill();if(i%stride===0||i===ps.length-1){x.fillStyle='#506078';x.fillText(monthLabel(p.label),Math.min(Math.max(45,p.x-15),w-58),h-10);x.fillStyle='#1478f2'}});bind(c,ps)}window.addEventListener('resize',()=>DATA&&render());
